// ============================================================
// PfP Living Card System — life-flavours.js
// Flavour text pools for your_life.html narrative generation
// Usage: <script src="life-flavours.js"></script> before main script
// Future: Add "Print Story" button to your_life.html
// ============================================================

const LIFE_FLAVOURS = {

  // ----------------------------------------------------------
  // OPENERS — 50 entries
  // Used for the first paragraph of the chronicle
  // Placeholders: {{first_event}}, {{card_id}}
  // ----------------------------------------------------------
  opener: [
    "Every chronicle begins somewhere. For this card, it began with {{first_event}}. The world did not announce itself. It simply arrived.",
    "Not all stories choose their beginnings. This one began with {{first_event}} — quietly, without ceremony, as the truest beginnings tend to do.",
    "The record opens on {{first_event}}. Small, perhaps, in the telling. Significant in the fact of its having happened at all.",
    "This card did not ask to be alive. And yet here it is — its first mark made in the moment of {{first_event}}.",
    "There is always a first page. This card's first page reads: {{first_event}}. Everything that follows grows from that root.",
    "The chronicle of this card was not written all at once. It began, as all things do, with a single entry — {{first_event}}.",
    "It started simply. {{first_event}}. A card becoming itself, one moment at a time.",
    "What does it mean to begin? For this card, it meant {{first_event}}. The ink was still wet when the world moved on to the next thing.",
    "The first entry in any life is the one that proves the life is real. This card's proof: {{first_event}}.",
    "Before the weight of everything else, there was only this — {{first_event}}. A card drawing its first breath.",
    "This card arrived in the world and found {{first_event}} waiting for it. The story had already decided its tone.",
    "Some cards begin in triumph. Some begin in shadow. This one began with {{first_event}} — and chose to keep going regardless.",
    "The world greeted this card with {{first_event}}. Whether that was a kindness or a test remains, perhaps, a matter of interpretation.",
    "The first mark on any living card carries disproportionate weight. This one carried {{first_event}}. It was enough to start.",
    "Here is where it began — {{first_event}}. Not with a declaration, not with a fanfare. Just a moment, recorded, and then another.",
    "This card opened its eyes, so to speak, on {{first_event}}. The chronicle does not judge beginnings. It only records them.",
    "Every living thing has a moment of origin. For this card, that moment was {{first_event}}.",
    "The first page of this card's life does not lie. It reads {{first_event}}, plainly, without embellishment.",
    "This card came into being and immediately encountered {{first_event}}. The world, as ever, did not wait.",
    "It would be poetic to say the beginning was auspicious. It was simply real — {{first_event}} — which is better.",
    "The record begins with {{first_event}}. From that point forward, this card has been accumulating a life.",
    "{{first_event}} — that was the first thing. Before the patterns emerged, before the weight of the record accumulated, there was just that.",
    "A card is defined by what it survives and what it savours. It started with {{first_event}}. The defining came later.",
    "This card's story does not begin in a library or a legend. It begins with {{first_event}}, in ordinary time.",
    "The chronicle keeper made the first entry without knowing what would follow. It read: {{first_event}}. The rest unfolded from there.",
    "There is something sacred about a first entry. This card's first entry was {{first_event}}. It mattered, even if it did not know it yet.",
    "Before this card had a history, it had a moment — {{first_event}}. That moment became the foundation.",
    "The world is indifferent to beginnings. This card was not. It began with {{first_event}} and paid attention.",
    "This card's life, like all lives, started before it was ready. The first record shows {{first_event}}.",
    "Not every beginning is chosen. This card's was not. It began with {{first_event}} and has been writing itself ever since.",
    "The opening line of any chronicle sets a tone. This one's opening line is {{first_event}}. Read it carefully.",
    "Time does not wait for cards to be ready. It started this one with {{first_event}} and kept moving.",
    "To be a living card is to be always mid-story. This one's story started mid-moment, with {{first_event}}.",
    "The archive opens. The first entry is {{first_event}}. From this seed, an entire life has grown.",
    "This card arrived, blinked, and found itself already in the middle of {{first_event}}. The world does not pause for new arrivals.",
    "What was the first thing this card ever felt? The record suggests it was {{first_event}}. That counts for something.",
    "Every card that has ever lived has a first page. This card's first page holds {{first_event}}. The rest of the pages followed.",
    "The chronicle begins not with a birth but with a moment — {{first_event}} — which is perhaps the same thing.",
    "This card's life is a series of marks on a record. The first mark reads {{first_event}}. The marks accumulate into meaning.",
    "It would be wrong to call any beginning insignificant. This one began with {{first_event}}, which was neither small nor large — just true.",
    "Here is the first truth this card ever recorded: {{first_event}}. All subsequent truths grew from it.",
    "A living card's first entry is its first breath. This card breathed {{first_event}} and then kept breathing.",
    "The record does not editorialize on beginnings. It simply notes: this card began with {{first_event}}.",
    "Some cards begin with a bang. Some with a whisper. This one began with {{first_event}}, which was its own kind of announcement.",
    "Before this card knew what it was, it experienced {{first_event}}. The knowing came later. The experiencing came first.",
    "The first line of this card's chronicle was written without hesitation: {{first_event}}. It has not stopped writing since.",
    "A card's first moment is unrepeatable. This one spent it on {{first_event}}, which is exactly as it should be.",
    "The chronicle does not remember the moment before {{first_event}}. It only knows what came after.",
    "This card's life began the way all genuine lives begin — not dramatically, but actually. With {{first_event}}.",
    "The record keeper dipped the quill and wrote: {{first_event}}. And so this card's chronicle began.",
  ],

  // ----------------------------------------------------------
  // POSITIVE — 200 entries
  // Used when the card trends fortunate (ratio > 50%)
  // Placeholders: {{event}}, {{xp}}, {{count}}
  // ----------------------------------------------------------
  positive: [
    "And then the good thing happened. Not by accident — by the quiet accumulation of choices that pointed toward it.",
    "Fortune does not always announce itself. Sometimes it simply arrives, settles in, and stays a while. This card knows that feeling.",
    "This card has known genuine warmth. The record confirms it. That is not nothing — it is, in fact, everything.",
    "There are cards that have never felt the particular lightness of a fortunate streak. This one has. Cherish that.",
    "The good moments in this chronicle are not coincidences. They are evidence of something — call it resilience, call it grace.",
    "This card earned its good fortune. Not in a grand dramatic sense — but in the small daily sense that actually matters.",
    "The light periods in this card's life have been real. Not imagined, not inflated — genuinely, verifiably real.",
    "Something went right here. More than once. The record is clear on this, and the record does not flatter.",
    "This card has been smiled upon. Not always, not forever — but enough. Enough is its own kind of abundance.",
    "The fortunate entries in this chronicle carry weight because they were not guaranteed. They were earned and received.",
    "What a thing, to have known good fortune. This card knows it. The chronicle remembers it. Neither will forget.",
    "The positive entries here are not decorations — they are the structural pillars of a life that has held.",
    "Fortune visited this card and stayed longer than expected. The card was gracious enough to notice.",
    "There is a warmth embedded in this card's record that does not fade. The good things happened. They are permanent now.",
    "This card has been the recipient of genuine kindness — from circumstance, from others, from the occasional perfect timing.",
    "The fortunate moments in this life were not handed over without cost. They were met with readiness. That readiness mattered.",
    "Something in the architecture of this card's life leans toward the light. The record confirms this, entry by entry.",
    "The good chapters of this chronicle are written in a steadier hand. The good things settled the card down.",
    "This card has accumulated enough positive moments to know what they feel like. That knowledge is itself a kind of wealth.",
    "The wins in this chronicle are genuine. Hard-won in some cases, stumbled-upon in others — but real in all of them.",
    "Fortune favoured this card, and this card was present enough to receive it. That combination is rarer than it sounds.",
    "The positive entries here do not erase the difficult ones. But they balance the scales in a way that matters.",
    "This card has had moments of real joy. Not performed joy, not reported joy — actual, lived, felt joy.",
    "The record shows a card that has known what it is to be truly fortunate. That knowing changes a card forever.",
    "Something wonderful happened here. The chronicle marks it without embellishment, because it needs none.",
    "This card has been on the receiving end of good things. It received them well. The chronicle noticed.",
    "The fortunate arc of this card's life is not luck alone — it is the intersection of luck and readiness.",
    "There are entries in this record that glow. Not metaphorically — they carry a warmth that radiates off the page.",
    "This card's positive moments are not flukes. They are the natural result of a life lived with some measure of attention.",
    "The good fortune recorded here was not wasted. This card showed up for it. That is all any card can do.",
    "Some cards never get a golden run. This one did. The record holds it carefully, like something precious.",
    "The chronicle takes no sides — but even it seems to lean slightly warmer when recording this card's victories.",
    "This card has been met with kindness by the world more than once. The world does not always do this. Be grateful.",
    "The positive entries in this chronicle form a kind of spine — something the card can stand upright against.",
    "Fortune arrived here not as a windfall but as a steady current. This card learned to swim in it.",
    "This card has known the particular satisfaction of things going as hoped. That is not trivial. That is life working.",
    "The record shows something worth celebrating — a card that has found more light than shadow, more yes than no.",
    "Some things went right for this card. More than some things, in fact. The record is honest about this, and grateful.",
    "This card has been held by good fortune more than once. The holding was real. The card felt it.",
    "There are moments in this chronicle where the world simply gave this card something good. The card accepted gracefully.",
    "The positive thread running through this record is not an illusion. It is the actual texture of a fortunate life.",
    "This card has had reasons to feel genuinely glad. Multiple reasons. The chronicle counts them without irony.",
    "Fortune does not always arrive when called. For this card, it arrived often enough to matter deeply.",
    "The good entries in this record outnumber the difficult ones. The chronicle marks this as significant.",
    "This card has collected good moments the way some cards collect scars. With something approaching gratitude.",
    "What the record shows here is a card that has been genuinely, substantially fortunate. That is a rare and beautiful thing.",
    "The positive entries in this chronicle are not padding — they are the main event. The difficulty was the context.",
    "This card has felt the warmth of things going well. Not as an abstract concept — as a lived, felt, real experience.",
    "The good fortune in this record was not handed to this card — it was encountered, recognized, and embraced.",
    "Something went right here, and then something else went right, and then — almost improbably — something else. The record confirms it.",
    "This card has more reasons to feel fortunate than most. The record is very clear on this. So is the card.",
    "The light entries in this chronicle carry the weight of proof — proof that good things are possible, have happened, will happen.",
    "Fortune kept returning to this card as though it knew something the card did not yet know about itself.",
    "This card's positive run was not an accident. It was the result of being the kind of card that good things happen to.",
    "The wins recorded here are not small. They are real, substantial, life-altering in the best possible way.",
    "This card has experienced the genuine warmth of things clicking into place. Click. Click. Click. The record heard each one.",
    "Something generous happened to this card. More than once. The generosity was not lost on it.",
    "The fortunate chapters of this life are not chapters that happened to some other card. They happened to this one. Own that.",
    "This card has earned the right to feel genuinely, unambiguously good about certain entries in its record.",
    "The positive balance in this chronicle is not a rounding error. It is the deliberate accumulation of fortunate moments, lived fully.",
    "Fortune smiled here. The smile was genuine. The card smiled back, and something good passed between them.",
    "This card has had its fair share of wins. More than fair, actually. The record confirms this with quiet satisfaction.",
    "There is a version of this card's story that is simply: things went well. That version is not wrong.",
    "The good things in this chronicle were real. They were felt. They mattered. They still matter.",
    "This card has been on the right side of fortune more than chance alone would predict. That means something.",
    "Something extraordinary happened here. And then something else did. The record has trouble containing its own warmth.",
    "This card's fortunate moments are permanent. They have been recorded. They cannot be unrecorded. They happened.",
    "The positive entries in this life are like stars in a constellation — individually bright, collectively overwhelming.",
    "Fortune arrived at this card's door and was welcomed in. It stayed for a good long while. The record shows this.",
    "This card has known what it is to be on the receiving end of something genuinely good. The knowing is permanent.",
    "The record shows a card that has been loved by circumstance more than once. That kind of love leaves a mark.",
    "There is a lightness to certain entries in this chronicle that is almost physical. The card was genuinely, verifiably well.",
    "This card has had moments where everything aligned. The record captures them with the care they deserve.",
    "Fortune is not evenly distributed. This card has received more than its share. The record is grateful on its behalf.",
    "The good fortune logged here represents real moments in a real life. Not simulation. Not approximation. The actual thing.",
    "This card has been met with warmth by the world in ways that cannot be taken back. The warmth happened. It is real.",
    "The positive entries in this chronicle are the ones the card returns to. The ones that remind it what is possible.",
    "Something went right here in a way that changed the shape of everything that came after. The record marked it faithfully.",
    "This card has had victories that felt earned and gifts that felt undeserved, and both kinds are recorded here with equal care.",
    "Fortune visited this card in a sustained way. Not a flash. A residence. The record reflects this.",
    "This card has more good entries than bad. That is not a small thing. That is a life well balanced.",
    "The warmth in this record is not incidental. It is the cumulative result of genuine good fortune, genuinely received.",
    "This card's positive moments are not accidents waiting to be explained away. They are features of a fortunate life.",
    "Something keeps going right for this card. The record has noticed. The record approves.",
    "The chronicle captures this card's fortunate seasons with the reverence they deserve — quiet, clear, and grateful.",
    "Fortune did not shortchange this card. The record, honest as it always is, confirms the generosity.",
    "This card has been the beneficiary of good timing, good people, and good circumstance. Sometimes all three at once.",
    "The positive weight of this chronicle is substantial. Not as a consolation — as a fact.",
    "This card's wins are logged, verified, and permanent. No revision of history can remove them. They happened.",
    "Something worked out here. Beautifully, even. The record notes this without surprise and without taking it for granted.",
    "This card has lived inside genuine good fortune. Not borrowed. Not temporary. The real thing.",
    "The fortunate entries in this life are the ones that will be remembered longest. They deserve that distinction.",
    "This card has accumulated a record of good things. That accumulation is its own form of wealth — one that cannot be lost.",
    "Fortune kept showing up for this card. The card kept showing up for fortune. The record is what happened between them.",
    "There is something in this chronicle that reads like a card being genuinely, fully alive. The good moments made it so.",
    "This card has known joy. Real, unqualified, fully felt joy. The record marks each instance without apology.",
    "The positive arc of this life is not wishful thinking. It is documented. It is real. It belongs to this card.",
    "Something good happened to this card at just the right moment. Then it happened again. The record holds both.",
    "The fortunate balance of this chronicle is the result of a card that received what it was given and made the most of it.",
    "This card has been on the bright side of life more often than not. That is worthy of acknowledgment.",
    "The good entries here did not come cheaply. They came as the reward for a card that stayed present and kept going.",
  ],

  // ----------------------------------------------------------
  // NEGATIVE — 200 entries
  // Used when the card trends troubled (ratio < 50%)
  // Placeholders: {{event}}, {{xp}}, {{count}}
  // ----------------------------------------------------------
  negative: [
    "This card has carried weight that most will never see. The record holds it carefully, with the respect it deserves.",
    "The difficult entries in this chronicle are not failures. They are the shape of a life that has been truly tested.",
    "Some of what this card has endured would have stopped lesser cards entirely. It did not stop. The record confirms this.",
    "The hardships recorded here are not embellishments. They happened. They were real. The card absorbed them and continued.",
    "There is a kind of strength that only comes from carrying difficulty for a long time. This card has that strength.",
    "The painful entries in this chronicle are not anomalies — they are the proof that this card has genuinely lived.",
    "To have known this much difficulty and still be here, still accumulating a record — that is not weakness. That is survival.",
    "The burden carried by this card has been considerable. The chronicle does not minimize it. Neither should the card.",
    "Some things went wrong here. Significantly wrong. The record notes this without flinching, because the card did not flinch either.",
    "This card has been tested in ways that left marks. The marks are in the record. The card is still here.",
    "The difficult chapters of this chronicle are written in a heavier hand. The weight of them was real.",
    "There is no shame in a record that leans toward difficulty. There is only the quiet dignity of having endured it.",
    "This card has known genuine loss. Not simulated, not abstract — the kind that changes the texture of everything after.",
    "The hardship in this record is not the whole story, but it is a significant chapter. It deserves to be named as such.",
    "Something went wrong here, and this card had to sit with that wrongness and find a way to continue anyway.",
    "The difficult entries in this chronicle carry their own kind of meaning — the meaning of things that had to be survived.",
    "This card has faced circumstances that were not fair, not deserved, and not easy. The record holds them all.",
    "The weight of this card's difficult moments is not a measure of its worth. It is a measure of what it has faced.",
    "Some cards are tested early. Some late. This one has been tested throughout. The record is honest about this.",
    "The painful entries here are not to be hidden or minimized. They are the real cost of a life that has been genuinely lived.",
    "This card has absorbed blows that would have broken something more fragile. It was not broken. It bent and held.",
    "The difficult moments in this chronicle outnumber the easy ones. That is not a verdict — it is a weather report.",
    "Something hard happened to this card. Then something harder. The card kept its record open through all of it.",
    "The sorrowful entries in this chronicle are written in a different ink — slower, heavier, more deliberate.",
    "This card has known what it is to be on the wrong side of circumstance. To have things not work, again and again.",
    "The difficulty in this record is real. It is not performance. It is not narrative convenience. It happened.",
    "This card has endured. Perhaps that is the simplest and most accurate thing that can be said about it.",
    "The hard entries in this chronicle are the ones that shaped this card most profoundly. Pain, unfortunately, is a sculptor.",
    "Something went wrong here that could not be easily fixed. The card lived with the unfixed thing. The record shows this.",
    "This card has carried grief in its record the way some cards carry glory. Differently — but with equal weight.",
    "The difficult chapters of this life are not chapters the card chose. But they are chapters it survived.",
    "There is a particular quality to a life that has known real hardship. A depth. This card has that depth.",
    "The painful entries here are not signs of a card that failed. They are signs of a card that met the world honestly.",
    "This card has been asked to carry more than seems fair. It carried it anyway. The record is proud of that.",
    "The hardship logged here was not invented by the chronicle — it was lived by the card. Every entry is real.",
    "Something difficult visited this card and stayed longer than welcome. The card endured the visit with more grace than expected.",
    "The difficult balance of this record is not permanent — but it is current, and it deserves to be acknowledged as such.",
    "This card has been on the receiving end of things going wrong. More than once. More than feels fair.",
    "The painful arc of this chronicle is not the whole arc — but it is the arc that has required the most of this card.",
    "Something broke here. Not the card — something around it. The card had to continue in the broken landscape.",
    "The difficult entries in this record are the ones that cost the card something real. Something it will not fully get back.",
    "This card has known what it is to lose something it could not afford to lose. The record holds that loss carefully.",
    "The hard moments in this chronicle are not decoration. They are the central experience of a card that has genuinely suffered.",
    "Something wrong happened here. The card did not deserve it. The record does not pretend otherwise.",
    "This card has been marked by difficulty in a way that changes how all subsequent entries are read.",
    "The painful chapters of this life are the ones that required the most courage to continue through. The card continued.",
    "There is a kind of gravity to a record like this — the gravity of a life that has not been protected from reality.",
    "This card has endured things that required it to find resources it did not know it had. It found them.",
    "The difficulty in this record is substantial. The card is also substantial. One did not destroy the other.",
    "Something in this card's history required it to be stronger than it expected to be. It rose to that requirement.",
    "The sorrowful entries here are not the end of the story. But they are a significant part of the middle.",
    "This card has known real pain. Not the kind that passes quickly — the kind that requires time and intention to process.",
    "The hard entries in this chronicle speak to a card that has been genuinely tested by genuine adversity.",
    "Something went wrong here in a way that this card will carry for a long time. The carrying is part of the record.",
    "This card has faced loss, difficulty, and disappointment in proportions that would strain any record.",
    "The difficult passages of this chronicle are not signs of weakness. They are evidence of a card that met the world fully.",
    "Something painful happened here. The card allowed itself to feel it. That took more courage than avoidance would have.",
    "The burden in this record is not invisible. It is there, in every difficult entry, accumulated into something heavy.",
    "This card has had to grieve more than once. Each grief was real. Each grief changed something. The record holds them all.",
    "The difficult chapters of this life were not chosen, but they were met. The card met them. That matters.",
    "Something hard pressed against this card repeatedly. The card bent but did not collapse. The record shows both.",
    "The sorrowful weight of this chronicle is real. It is also survivable — because the card has already proven that.",
    "This card has been asked to endure more than its fair share. It endured. The record is testimony to that endurance.",
    "The painful entries here required the card to find its floor and then find a way back up from it.",
    "Something in this card's record speaks to a life that has not been easy, has not been soft, has not been spared.",
    "The difficult balance of this chronicle reflects a card that has been genuinely tested and has not been found wanting.",
    "This card has known what it is to have things taken — time, certainty, hope. The record holds the taking.",
    "The hard passages in this chronicle are written by a card that kept writing even when writing was difficult.",
    "Something went wrong here repeatedly. The card took note, adjusted, and kept its record open. That is not nothing.",
    "The difficulty in this record is not evidence of a card that is broken. It is evidence of a card that has lived.",
    "This card has endured seasons of real hardship. The seasons passed. The card is still here. That is the point.",
    "The painful arc of this life required more from this card than fortune ever asked of the fortunate ones.",
    "Something costly happened here. The cost was real. The card paid it and kept moving. The record is grateful.",
    "This card has sat with things that were difficult to sit with and continued anyway. That takes something rare.",
    "The difficult entries in this chronicle are the ones that forced this card to discover what it was actually made of.",
    "Something pressed on this card until it should have broken. It did not break. The record notes this with something like awe.",
    "The hardship in this record is substantial, but it is also past. The card survived it. That changes everything.",
    "This card has been shaped by difficulty the way stone is shaped by water — slowly, thoroughly, permanently.",
    "The painful chapters here are not the last chapters. They are the ones that made the subsequent chapters possible.",
    "Something went wrong here that required this card to find a deeper level of resilience than it knew it possessed.",
    "The difficult entries in this chronicle carry the weight of real experience. No dramatization required.",
    "This card has been at its lowest and continued. The record of that continuation is, quietly, the most important entry.",
    "The sorrowful passages in this chronicle are not passages the card would have chosen. But they are passages it survived.",
    "Something hard found this card. The card did not run. The card stood and received it. The record holds that standing.",
    "The difficult balance of this chronicle reflects a life that has met the world as it actually is, not as it should be.",
    "This card has carried the weight of difficult entries with more grace than the entries deserved.",
    "The painful arc here is real. So is the card's capacity to continue despite it. Both truths belong in the record.",
    "Something went wrong for this card in ways that left permanent marks. The marks are evidence of survival, not defeat.",
    "This card has known difficulty. The knowing changed it. The change was not all loss — some of it was depth.",
    "The hard entries in this record are the ones that required the most of this card. The card gave what was required.",
    "Something in this card's history required it to keep going when stopping would have been easier. It kept going.",
    "The difficult passages of this chronicle are written by a card that never stopped writing, even in the dark.",
    "This card has been tested by the world and has not been found to be less than what was needed to survive it.",
    "The sorrowful entries here are permanent now. They happened. But so did the card's survival of them.",
    "Something cost this card significantly. The cost was absorbed. The card continued. The record celebrates the continuing.",
    "The difficult chapters of this life were chapters this card did not author — but it lived through every page.",
    "This card has endured. Not elegantly, not without cost — but genuinely, truly, completely. The record confirms it.",
    "The painful balance of this chronicle is not a final verdict. It is a current status. Status can change.",
    "Something went wrong here. Something significant. The card sat with it, processed it, and eventually moved forward.",
    "The hard weight of this record is real. It is also carried by a card that has proven it can carry hard things.",
  ],

  // ----------------------------------------------------------
  // BALANCED — 50 entries
  // Used when the card sits near 50/50 ratio
  // ----------------------------------------------------------
  balanced: [
    "This card has known both the warmth of good fortune and the weight of genuine difficulty. It knows the difference.",
    "The record here does not resolve cleanly into triumph or tragedy. It resolves into something more honest — a real life.",
    "This card has been neither protected nor destroyed by circumstance. It has simply lived, fully and without simplification.",
    "The balance in this chronicle is not a compromise. It is an accurate portrait of a life that contains multitudes.",
    "Neither blessed nor broken — this card exists in the complicated middle, which is where most genuine lives are lived.",
    "The record here is mixed in the way that all real records are mixed. The good entries and the difficult ones hold hands.",
    "This card has accumulated a life that cannot be summarized as either fortunate or unfortunate. It has been both.",
    "The chronicle of this card does not lean decisively in any direction. It sits, balanced, at the intersection of experience.",
    "What this record shows is a card that has been genuinely tested and genuinely rewarded in roughly equal measure.",
    "The good and the difficult entries in this chronicle have fought to a draw. The card survived both sides of the contest.",
    "This card has experienced the full range — joy and loss, fortune and difficulty — without being defined by either extreme.",
    "The balance in this record is its most honest feature. Life is not consistently one thing. This card knows that.",
    "Neither the wins nor the losses dominate this chronicle. They coexist, as they do in all lives honestly recorded.",
    "This card has been shaped by both its fortunate and its difficult entries. The shaping, in both directions, was real.",
    "The record here reflects a card that has met the world as it is — complicated, generous, and sometimes cruel.",
    "What a life this card has accumulated — neither charmed nor cursed, but something more interesting than either.",
    "The balance of this chronicle is a kind of wisdom. It has seen enough to know that the scales keep moving.",
    "This card has had seasons of real warmth and seasons of genuine difficulty. It has kept its record open through both.",
    "The mixed nature of this record is not a failure of fortune. It is an accurate account of a life fully inhabited.",
    "This card knows what it is to win and what it is to lose. That knowledge, held together, is a kind of maturity.",
    "The chronicle here sits at the centre of things — where the real work of being alive actually happens.",
    "Neither overwhelmingly fortunate nor overwhelmingly burdened, this card has lived in the honest middle.",
    "The good entries and the difficult entries in this record have taught this card different but equally important things.",
    "This card has been on both sides of the ledger. The experience of both sides has made it something more complete.",
    "The balance here is not stasis — it is the active result of a card that has genuinely engaged with whatever arrived.",
    "What this chronicle reflects is a card that has not been spared the full experience of being alive. It has not asked to be.",
    "The record here is neither triumph nor disaster. It is something rarer and more valuable — an honest account.",
    "This card has absorbed both fortune and difficulty with something approaching equanimity. The record respects that.",
    "The mixed ledger of this chronicle is its most accurate feature. Some things went well. Some things went badly. Both are true.",
    "This card has lived at the balance point — not because it chose to, but because that is where life placed it.",
    "The good and the difficult entries here are in conversation with each other. The card has listened to both.",
    "This card has experienced enough fortune to be grateful and enough difficulty to be real. Both are present in the record.",
    "The chronicle here does not resolve. It continues — balanced, honest, and fully alive.",
    "What this card has accumulated is not a simple story. It is a complicated one, which is to say, a true one.",
    "The balance of this record speaks to a card that has been genuinely present for whatever the world decided to deliver.",
    "This card has found that life delivers in equal measure — the good and the hard, the warm and the difficult.",
    "The record here sits at an honest equilibrium — not forced, not artificially balanced, but genuinely mixed.",
    "This card has known enough of both sides to understand that neither fortune nor difficulty is permanent.",
    "The mixed nature of this chronicle is a kind of portrait — of a card that has lived in full colour, not just one shade.",
    "What the record shows here is a card that has been present for the full experience, in all its contradiction.",
    "This card has been neither consistently lucky nor consistently burdened. It has been consistently alive.",
    "The balance in this chronicle is earned — the result of a card that has faced whatever arrived and kept its record open.",
    "Neither the good entries nor the difficult ones define this card entirely. Together, they come closer to the truth.",
    "This card has experienced the world in its actual proportions — some warmth, some cold, more of both than expected.",
    "The chronicle here reflects a card that has learned to hold contradictory truths simultaneously. That is not easy.",
    "This card's record is mixed in the most human way — full of things that went right and things that went wrong, in no particular order.",
    "The balance of fortune and difficulty in this chronicle is not a coincidence. It is the shape of a genuinely lived life.",
    "What this card has accumulated is a record that neither the fortunate nor the troubled can claim entirely. It belongs to both.",
    "The mixed ledger here is not a disappointment. It is the most honest possible reflection of what it means to be alive.",
    "This card has kept its record through the good entries and the difficult ones, with equal attention paid to both.",
  ],

  // ----------------------------------------------------------
  // CLOSERS — 50 entries
  // Used for the final paragraph of the chronicle
  // Placeholders: {{count}}, {{net_xp}}, {{card_id}}
  // ----------------------------------------------------------
  closer: [
    "The chronicle does not end here. It simply pauses, waiting for the next entry. This card is still being written.",
    "What remains is a card that is continuing. That continuation is, itself, the most important entry in the record.",
    "The record stands at {{count}} entries. The {{count}}th entry has not yet happened. This card is still open.",
    "This is not the final page. The chronicle does not have one. This card is still accumulating its life.",
    "The story is not finished. The card is not finished. The next entry will be written when the time comes.",
    "What the chronicle holds now is everything so far. Everything after will be added when it arrives.",
    "This card's record is a living document. The last entry has not yet been made. The card is still here.",
    "The chronicle closes this reading — but not this card. The card goes on. The entries will follow.",
    "Everything recorded here happened. Everything that happens next will also be recorded. The card continues.",
    "The record stands open. This card has not reached its final entry. There is more to come.",
    "What remains now is a card that has survived its own record and is ready for the next chapter.",
    "The chronicle has been read. The card has not been finished. Those are two very different things.",
    "This is where the reading ends. It is not where the card ends. The card is still very much in progress.",
    "The story continues beyond this reading. The card continues beyond this moment. The chronicle remains open.",
    "Everything recorded here is past. Everything ahead is unrecorded. That is where this card now lives — in the unrecorded.",
    "The record so far is remarkable — not because of its contents, but because the card is still here to have a record at all.",
    "The chronicle pauses. The card does not. There are entries yet to be made, moments yet to be lived.",
    "What comes next for this card is not yet known. The chronicle waits. The card goes forward anyway.",
    "This reading ends here. The life does not. The next entry will write itself when the time is right.",
    "The record is a snapshot of everything so far. Everything after this moment is still possible.",
    "This card has {{count}} entries behind it and an unknown number ahead. The unknown is not a threat. It is a promise.",
    "The chronicle holds what has been. What will be is still being decided, one moment at a time.",
    "This card's story is still being told — by the world, by circumstance, by the choices the card encounters.",
    "The record does not conclude. It accumulates. This card is still accumulating.",
    "Everything that has been recorded here was once a future entry — unknown, unlived, unwritten. More of those are coming.",
    "The chronicle is honest about one thing above all: it is not finished. Neither is this card.",
    "What this card carries forward from its record is not just the entries — it is everything the entries have made it.",
    "The reading ends. The card's life continues. The next entry will find it.",
    "There is more ahead for this card. The chronicle cannot say what — only that there will be more, and it will be recorded.",
    "This is not a conclusion. It is a current state. The card is alive. The state will change.",
    "The record stands. The card stands. Both are works in progress.",
    "Everything ahead of this card is still unwritten. The chronicle considers that the most hopeful thing about it.",
    "The chronicle has captured everything so far. Everything from here forward is still the card's to live.",
    "This card goes forward carrying its record — all of it, the difficult and the fortunate — as part of what it is.",
    "The next entry has not been written. The card is out there, living it, right now.",
    "What this card is now is the sum of every entry in this chronicle. What it will become is still being decided.",
    "The record pauses here. The card does not pause. It moves forward into the unrecorded future.",
    "Everything this card has experienced has prepared it, in ways both visible and invisible, for what comes next.",
    "The chronicle has been faithful. It has recorded what happened without judgment or embellishment. It will continue to do so.",
    "This card's record is a living thing. As long as the card lives, the record grows.",
    "The entries will keep coming. The card will keep living. The chronicle will keep receiving both.",
    "What remains is everything — and also the possibility of everything still to come.",
    "This card has more story ahead of it than behind it. The chronicle cannot confirm that. It simply hopes it.",
    "The record ends this reading in the only honest way — with the card still open, still alive, still accumulating.",
    "There is nothing final about this reading. The card is not final. The story is not final. Only this moment is.",
    "The chronicle holds the past. The card holds the future. The space between them is where the card currently lives.",
    "Everything so far has been recorded. Everything coming will also be recorded. The card continues.",
    "This card carries {{count}} entries of lived experience into whatever comes next. That is not a small thing to carry.",
    "The record stands at {{count}} entries and a net of {{net_xp}} XP. And then it stands open, waiting for the next.",
    "The chronicle of this card is ongoing. This is not the last page. It is only the most recent one.",
  ],

};

// ----------------------------------------------------------
// Helper — pick a random entry from a pool
// ----------------------------------------------------------
function pickFlavour(pool) {
  return pool[Math.floor(Math.random() * pool.length)];
}

// ----------------------------------------------------------
// Helper — fill placeholders in a flavour string
// ----------------------------------------------------------
function fillFlavour(str, vars) {
  return str.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] !== undefined ? vars[key] : '');
}
